filmapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', views.home, name='home'),
    path('admin_posts/', views.admin_posts, name='admin_posts'),
    path('create/', views.create_blog, name='create_blog'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout_user'),
    path('blog/<int:pk>/', views.blog_detail, name='blog_detail'),
    path('contact/', views.contact, name='contact'),
    path('guest/', views.guest_reviews, name='guest'),
    path('search/', views.search, name='search'),
    path('author/<int:author_id>/', views.author_posts, name='author_posts'),
    

]

# Serve media files during development.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filmshift/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('filmapp.urls', 'filmapp'), namespace='filmapp')),

]



filmapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='blog_images/', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

filmapp/forms.py
from django import forms
from .models import Blog, Contact
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact  
        fields = ['name', 'email', 'message'] 

    def save(self, commit=True):
        instance = super().save(commit=False)
        # Perform any additional processing or validation here if needed
        if commit:
            instance.save()
        return instance

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'image']



filmapp/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Blog
from .forms import BlogForm, RegistrationForm, ContactForm
from django.core.paginator import Paginator


def home(request):
    # Retrieve all blog posts
    all_blogs = Blog.objects.all().order_by('-created_at')

    # Set the number of blog posts to display per page
    blogs_per_page = 3

    # Create a Paginator instance
    paginator = Paginator(all_blogs, blogs_per_page)

    # Get the current page number from the request's GET parameters
    page_number = request.GET.get('page')

    # Get the Page object for the current page
    page = paginator.get_page(page_number)

    return render(request, 'filmapp/home.html', {'page': page})

def admin_posts(request):
    # Retrieve all blog posts
    admin_blogs = Blog.objects.filter(author__is_superuser=True).order_by('-created_at')

    # Set the number of blog posts to display per page
    blogs_per_page = 3

    # Create a Paginator instance
    paginator = Paginator(admin_blogs, blogs_per_page)

    # Get the current page number from the request's GET parameters
    page_number = request.GET.get('page')

    # Get the Page object for the current page
    page = paginator.get_page(page_number)

    return render(request, 'filmapp/admin_posts.html', {'page': page})



def guest_reviews(request):
    guest_posts = Blog.objects.filter(author__is_superuser=False).order_by('-created_at')

    blogs_per_page = 3

    paginator = Paginator(guest_posts, blogs_per_page)

    page_number = request.GET.get('page')

    page = paginator.get_page(page_number)

    return render(request, 'filmapp/guest_reviews.html', {'page': page})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():  # Correct the condition here
            form.save()  # Save the form data to the database
            return redirect("filmapp:login")  # Redirect to a success page or URL

    else:
        form = ContactForm()

    return render(request, 'filmapp/contact.html', {'form': form})

@login_required(login_url='filmapp:login')  # Add this decorator to require authentication.
def create_blog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)  # Include request.FILES for file uploads
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user  # Assign the logged in user as the author
            blog.save()
            return redirect('filmapp:home')
    else:
        form = BlogForm()
    
    return render(request, 'filmapp/create_blog.html', {'form': form})


def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('filmapp:login')
    return render(request, 'filmapp/auth/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('filmapp:home') 
    else:
        form = AuthenticationForm()
    
    return render(request, 'filmapp/auth/login.html', {'form': form})

def logout_user(request):
    logout(request)
    return redirect('filmapp:login')

def blog_detail(request, pk):
    blog = Blog.objects.get(pk=pk)
    return render(request, "filmapp/blog_detail.html", {"blog": blog})

def search(request):
    query = request.GET.get('q')  # Get the search query from the request's GET parameters
    results = []

    if query:
        # Perform a search query using your model's fields
        results = Blog.objects.filter(title__icontains=query)  # Example: Search in the 'title' field

    return render(request, 'filmapp/search_results.html', {'query': query, 'results': results})

def author_posts(request, author_id):
    author = get_object_or_404(User, id=author_id)  # Retrieve the author by their User ID
    author_posts = Blog.objects.filter(author=author)

    return render(request, 'filmapp/author_posts.html', {'author': author, 'author_posts': author_posts})


import requests
from bs4 import BeautifulSoup

def trending(request):
    url = 'https://www.rottentomatoes.com/browse/tv_series_browse/'
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    series_list_div = soup.find('div', class_='discovery-tiles__wrap')

    titles = []
    images = []
    audience_scores = []

    for series_div in series_list_div.find_all('div', class_='js-tile-link'):
        title = series_div.find('span', {'class': 'p--small', 'data-qa': 'discovery-media-list-item-title'}).text.strip()
        titles.append(title)

        image_url = series_div.find('img', class_='posterImage')['src']
        images.append(image_url)

        audience_score_elem = series_div.find('score-pairs', {'audiencescore': True})
        if audience_score_elem:
            audience_score_str = audience_score_elem['audiencescore']
            audience_score = int(audience_score_str)
            
            if 70 <= audience_score <= 100:
                audience_scores.append(audience_score)

    audience_scores.sort(reverse=True)

    series_data = zip(titles, images, audience_scores)

    return render(request, 'filmapp/trending.html', {
        'series_data': series_data
    })




filmapp/templates/filmapp/add_comment_to_blog.html
{% extends "filmapp/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9 main-content">
            <div class="blog-container">
                {% if blog.image %}
                <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image">
                {% endif %}
                <h2 class="blog-title">{{ blog.title }}</h2>
                <p class="blog-meta">Posted on {{ blog.created_at|date:"F d, Y" }} | by <a href="{% url 'filmapp:author_posts' author_id=blog.author.id %}">{{ blog.author.username }}</a></p>
                {{ blog.content }}
            </div>

            <!-- Add a Comment Form -->
            <h2>Add a Comment</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.content.label_tag }}
                    {{ form.content }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>

<!-- Sidebar Column -->
<div class="col-md-2 p-3" style="background-color: #f5ebeb; color: #888585; border-right: 1px solid #ccc; box-shadow: 2px 0px 4px rgba(0, 0, 0, 0.1);">
    <ul class="list-unstyled">
        {% if user.is_authenticated %}
        <!-- Display this if the user is logged in -->
        <li class="mb-2">
            <p>You are logged in as <strong>{{ user.username }}</strong></p>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="{% url 'filmapp:logout_user' %}">
                <i class="fa fa-sign-out mr-2"></i> Log Out
            </a>
        </li>
        {% else %}
        <!-- Display this if the user is not logged in -->
        <li class="mb-2">
            <a class="nav-link" href="/login/">
                <i class="fa fa-sign-in mr-2"></i> Log In
            </a>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="/register/">
                <i class="fa-solid fa-user-plus"></i> Register
            </a>
        </li>
        {% endif %}
    </ul>
</div>

<style>
        /* General styles */
        body {
            background-color: #f7f7f7;
            font-family: Arial, sans-serif;
        }
        .header {
            background-color: #292a2c;
            color: #ffffff;
            padding: 20px 0;
        }

        /* Main content styles */
        .main-content {
            background-color: #ffffff;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-top: 20px;
        }

        /* Sidebar styles */
        .sidebar {
            background-color: #f5ebeb;
            color: #888585;
            box-shadow: -4px 0px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }

        /* Blog container styles */
        .blog-container {
            padding: 20px;
            border: 1px solid #ddd;
            background-color: #fff;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        /* Blog image styles */
        .blog-image {
            max-width: 100%;
            height: 200px;
            object-fit: cover;
            border-radius: 5px;
        }
</style>

{% endblock %}

filmapp/templates/filmapp/admin_posts.html
{% extends "filmapp/base.html" %}

{% load custom_filters %}

{% block title %} FilmShift | {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Blogs Column -->
        <div class="col-md-10">
            <!-- Display blog posts in a grid with padding -->
            <div class="row">
                {% for blog in page %}
                <div class="col-md-4 mb-4">
                    <div class="blog-container">
                        <!-- Blog content -->
                        {% if blog.image %}
                        <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image">
                        {% endif %}
                        <h2 class="blog-title">{{ blog.title }}</h2>
                        <p class="blog-meta">Posted on {{ blog.created_at|date:"F d, Y" }} | by <a href="{% url 'filmapp:author_posts' author_id=blog.author.id %}">{{ blog.author.username }}</a> </p>
                        {{ blog.content|slice_and_ellipsis:200 }}<a href="{% url 'filmapp:blog_detail' pk=blog.id %}">[Read More]</a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %} <!-- Open a new row after every 3 columns -->
                </div><div class="row">{% endif %}
                {% endfor %}
            </div>
            
            <!-- Pagination controls -->
            <div class="pagination mt-4">
                <span class="step-links">
                    {% if page.has_previous %}
                    <a href="?page=1" class="btn btn-primary btn-sm">&laquo; First</a>
                    <a href="?page={{ page.previous_page_number }}" class="btn btn-primary btn-sm">Previous</a>
                    {% endif %}

                    <span class="current-page">{{ page.number }}</span>

                    {% if page.has_next %}
                    <a href="?page={{ page.next_page_number }}" class="btn btn-primary btn-sm">Next</a>
                    <a href="?page={{ page.paginator.num_pages }}" class="btn btn-primary btn-sm">Last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
        
<!-- Sidebar Column -->
<div class="col-md-2 p-3" style="background-color: #f5ebeb; color: #888585; border-right: 1px solid #ccc; box-shadow: 2px 0px 4px rgba(0, 0, 0, 0.1);">
    <ul class="list-unstyled">
        {% if user.is_authenticated %}
        <!-- Display this if the user is logged in -->
        <li class="mb-2">
            <p>You are logged in as <strong><a href="{% url 'filmapp:author_posts' author_id=user.id %}">{{ user.username }}</a></strong></p>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="{% url 'filmapp:logout_user' %}">
                <i class="fa fa-sign-out mr-2"></i> Log Out
            </a>
        </li>
        {% else %}
        <!-- Display this if the user is not logged in -->
        <li class="mb-2">
            <a class="nav-link" href="/login/">
                <i class="fa fa-sign-in mr-2"></i> Log In
            </a>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="/register/">
                <i class="fa-solid fa-user-plus"></i> Register
            </a>
        </li>
        {% endif %}
    </ul>
</div>

<style>
        /* General styles */
        body {
            background-color: #f7f7f7;
            font-family: Arial, sans-serif;
        }
        .header {
            background-color: #292a2c;
            color: #ffffff;
            padding: 20px 0;
        }

        /* Main content styles */
        .main-content {
            background-color: #ffffff;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-top: 20px;
        }

        /* Sidebar styles */
        .sidebar {
            background-color: #f5ebeb;
            color: #888585;
            box-shadow: -4px 0px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }

        /* Blog container styles */
        .blog-container {
            padding: 20px;
            border: 1px solid #ddd;
            background-color: #fff;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        .blog-image {
    max-width: 100%;
    height: 200px; /* Set a fixed height for all images */
    object-fit: cover;
    border-radius: 5px;
    display: block; /* Center-align the image horizontally */
    margin: 0 auto; /* Center-align the image horizontally */

}


</style>
{% endblock %}

filmapp/templates/filmapp/blog_detail.html
{% extends "filmapp/base.html" %}

{% load static %}

    {% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 main-content">
                <div class="blog-container">
                    {% if blog.image %}
                    <div class="text-center"> <!-- Center-align the image -->
                        <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image">
                    </div>
                    {% endif %}
                    <h2 class="blog-title text-center">{{ blog.title }}</h2> <!-- Center-align the title -->
                    <p class="blog-meta text-center"> <!-- Center-align the meta information -->
                        Posted on {{ blog.created_at|date:"F d, Y" }} | by
                        <a href="{% url 'filmapp:author_posts' author_id=blog.author.id %}">{{ blog.author.username }}</a>
                    </p>
                    {{ blog.content }}
                </div>
            </div>
    
    
        <!-- Sidebar Column -->
        <div class="col-md-2 p-3" style="background-color: #f5ebeb; color: #888585; border-right: 1px solid #ccc; box-shadow: 2px 0px 4px rgba(0, 0, 0, 0.1);">
            <ul class="list-unstyled">
                {% if user.is_authenticated %}
                <!-- Display this if the user is logged in -->
                <li class="mb-2">
                    <p>You are logged in as <strong>{{ user.username }}</strong></p>
                </li>
                <li class="mb-2">
                    <a class="nav-link" href="{% url 'filmapp:logout_user' %}">
                        <i class="fa fa-sign-out mr-2"></i> Log Out
                    </a>
                </li>
                {% else %}
                <!-- Display this if the user is not logged in -->
                <li class="mb-2">
                    <a class="nav-link" href="/login/">
                        <i class="fa fa-sign-in mr-2"></i> Log In
                    </a>
                </li>
                <li class="mb-2">
                    <a class="nav-link" href="/register/">
                        <i class="fa-solid fa-user-plus"></i> Register
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
        

    

<style>
    /* General styles */
    body {
        background-color: #f7f7f7;
        font-family: Arial, sans-serif;
    }
    .header {
        background-color: #292a2c;
        color: #ffffff;
        padding: 20px 0;
    }

    /* Main content styles */
    .main-content {
        background-color: #ffffff;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin-top: 20px;
    }

    /* Sidebar styles */
    .sidebar {
        background-color: #f5ebeb;
        color: #888585;
        box-shadow: -4px 0px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }

    /* Blog container styles */
    .blog-container {
        padding: 20px;
        border: 1px solid #ddd;
        background-color: #fff;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

    /* Blog image styles */
    .blog-image {
        max-width: 100%; /* Ensure the image scales to fit its container */
        height: auto; /* Maintain aspect ratio */
        object-fit: cover; /* Crop and center the image within its container */
        border-radius: 5px;
        width: 500px; /* Set a fixed width */
        height: 300px; /* Set a fixed height */
    }

</style>
    
    {% endblock %}

</body>
</html>

filmapp/templates/filmapp/guest_reviews.html
{% extends "filmapp/base.html" %}

{% load custom_filters %}

{% block title %} FilmShift | {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Blogs Column -->
        <div class="col-md-10">
            <!-- Display blog posts in a grid with padding -->
            <div class="row">
                {% for blog in page %}
                <div class="col-md-4 mb-4">
                    <div class="blog-container">
                        <!-- Blog content -->
                        {% if blog.image %}
                        <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image">
                        {% endif %}
                        <h2 class="blog-title">{{ blog.title }}</h2>
                        <p class="blog-meta">Posted on {{ blog.created_at|date:"F d, Y" }} | by <a href="{% url 'filmapp:author_posts' author_id=blog.author.id %}"> {{ blog.author.username }} </a> </p>
                        {{ blog.content|slice_and_ellipsis:200 }}<a href="{% url 'filmapp:blog_detail' pk=blog.id %}">[Read More]</a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %} <!-- Open a new row after every 3 columns -->
                </div><div class="row">{% endif %}
                {% endfor %}
            </div>
            
            <!-- Pagination controls -->
            <div class="pagination mt-4">
                <span class="step-links">
                    {% if page.has_previous %}
                    <a href="?page=1" class="btn btn-primary btn-sm">&laquo; First</a>
                    <a href="?page={{ page.previous_page_number }}" class="btn btn-primary btn-sm">Previous</a>
                    {% endif %}

                    <span class="current-page">{{ page.number }}</span>

                    {% if page.has_next %}
                    <a href="?page={{ page.next_page_number }}" class="btn btn-primary btn-sm">Next</a>
                    <a href="?page={{ page.paginator.num_pages }}" class="btn btn-primary btn-sm">Last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
        
<!-- Sidebar Column -->
<div class="col-md-2 p-3" style="background-color: #f5ebeb; color: #888585; border-right: 1px solid #ccc; box-shadow: 2px 0px 4px rgba(0, 0, 0, 0.1);">
    <ul class="list-unstyled">
        {% if user.is_authenticated %}
        <!-- Display this if the user is logged in -->
        <li class="mb-2">
            <p>You are logged in as <strong><a href="{% url 'filmapp:author_posts' author_id=user.id %}">{{ user.username }}</a></strong></p>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="{% url 'filmapp:logout_user' %}">
                <i class="fa fa-sign-out mr-2"></i> Log Out
            </a>
        </li>
        {% else %}
        <!-- Display this if the user is not logged in -->
        <li class="mb-2">
            <a class="nav-link" href="/login/">
                <i class="fa fa-sign-in mr-2"></i> Log In
            </a>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="/register/">
                <i class="fa fa-edit mr-2"></i> Register
            </a>
        </li>
        {% endif %}
    </ul>
</div>
        
    </div>
</div>


    </div>
</div>

<style>
        /* General styles */
        body {
            background-color: #f7f7f7;
            font-family: Arial, sans-serif;
        }
        .header {
            background-color: #292a2c;
            color: #ffffff;
            padding: 20px 0;
        }

        /* Main content styles */
        .main-content {
            background-color: #ffffff;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-top: 20px;
        }

        /* Sidebar styles */
        .sidebar {
            background-color: #f5ebeb;
            color: #888585;
            box-shadow: -4px 0px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }

        /* Blog container styles */
        .blog-container {
            padding: 20px;
            border: 1px solid #ddd;
            background-color: #fff;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        /* Blog image styles */
        .blog-image {
            max-width: 100%;
            height: 200px;
            object-fit: cover;
            border-radius: 5px;
        }
</style>
{% endblock %}

filmapp/templates/filmapp/home.html
{% extends "filmapp/base.html" %}

{% load custom_filters %}

{% block title %} FilmShift | {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Blogs Column -->
        <div class="col-md-10">
            <!-- Display blog posts in a grid with padding -->
            <div class="row">
                {% for blog in page %}
                <div class="col-md-4 mb-4">
                    <div class="blog-container">
                        <!-- Blog content -->
                        {% if blog.image %}
                        <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image">
                        {% endif %}
                        <h2 class="blog-title">{{ blog.title }}</h2>
                        <p class="blog-meta">Posted on {{ blog.created_at|date:"F d, Y" }} | by <a href="{% url 'filmapp:author_posts' author_id=blog.author.id %}">{{ blog.author.username }}</a> </p>
                        {{ blog.content|slice_and_ellipsis:200 }}<a href="{% url 'filmapp:blog_detail' pk=blog.id %}">[Read More]</a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %} <!-- Open a new row after every 3 columns -->
                </div><div class="row">{% endif %}
                {% endfor %}
            </div>
            
            <!-- Pagination controls -->
            <div class="pagination mt-4">
                <span class="step-links">
                    {% if page.has_previous %}
                    <a href="?page=1" class="btn btn-primary btn-sm">&laquo; First</a>
                    <a href="?page={{ page.previous_page_number }}" class="btn btn-primary btn-sm">Previous</a>
                    {% endif %}

                    <span class="current-page">{{ page.number }}</span>

                    {% if page.has_next %}
                    <a href="?page={{ page.next_page_number }}" class="btn btn-primary btn-sm">Next</a>
                    <a href="?page={{ page.paginator.num_pages }}" class="btn btn-primary btn-sm">Last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
        
<!-- Sidebar Column -->
<div class="col-md-2 p-3" style="background-color: #f5ebeb; color: #888585; border-right: 1px solid #ccc; box-shadow: 2px 0px 4px rgba(0, 0, 0, 0.1);">
    <ul class="list-unstyled">
        {% if user.is_authenticated %}
        <!-- Display this if the user is logged in -->
        <li class="mb-2">
            <p>You are logged in as <strong><a href="{% url 'filmapp:author_posts' author_id=user.id %}">{{ user.username }}</a></strong></p>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="{% url 'filmapp:logout_user' %}">
                <i class="fa fa-sign-out mr-2"></i> Log Out
            </a>
        </li>
        {% else %}
        <!-- Display this if the user is not logged in -->
        <li class="mb-2">
            <a class="nav-link" href="/login/">
                <i class="fa fa-sign-in mr-2"></i> Log In
            </a>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="/register/">
                <i class="fa-solid fa-user-plus"></i> Register
            </a>
        </li>
        {% endif %}
    </ul>
</div>

<style>
        /* General styles */
        body {
            background-color: #f7f7f7;
            font-family: Arial, sans-serif;
        }
        .header {
            background-color: #292a2c;
            color: #ffffff;
            padding: 20px 0;
        }

        /* Main content styles */
        .main-content {
            background-color: #ffffff;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-top: 20px;
        }

        /* Sidebar styles */
        .sidebar {
            background-color: #f5ebeb;
            color: #888585;
            box-shadow: -4px 0px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }

        /* Blog container styles */
        .blog-container {
            padding: 20px;
            border: 1px solid #ddd;
            background-color: #fff;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        .blog-image {
    max-width: 100%;
    height: 200px; /* Set a fixed height for all images */
    object-fit: cover;
    border-radius: 5px;
    display: block; /* Center-align the image horizontally */
    margin: 0 auto; /* Center-align the image horizontally */

}


</style>
{% endblock %}

filmapp/templates/filmapp/search_results.html
{% extends "filmapp/base.html" %}
{% block title %}Search Results | FilmShift{% endblock %}
{% block content %}
<div class="container">
    <h1>Search Results</h1>
    <p>Search query: "{{ query }}"</p>
    <ul>
        {% for result in results %}
            <li><a href="{% url 'filmapp:blog_detail' pk=result.pk %}">{{ result.title }}</a></li>
        {% empty %}
            <p>No results found.</p>
        {% endfor %}
    </ul>
</div>

<style>
    /* General styles */
    body {
        background-color: #f7f7f7;
        font-family: Arial, sans-serif;
    }
    .header {
        background-color: #292a2c;
        color: #ffffff;
        padding: 20px 0;
    }

    /* Main content styles */
    .main-content {
        background-color: #ffffff;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin-top: 20px;
    }

    /* Sidebar styles */
    .sidebar {
        background-color: #f5ebeb;
        color: #888585;
        box-shadow: -4px 0px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }

    /* Blog container styles */
    .blog-container {
        padding: 20px;
        border: 1px solid #ddd;
        background-color: #fff;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

    /* Blog image styles */
    .blog-image {
        max-width: 100%;
        height: 200px;
        object-fit: cover;
        border-radius: 5px;
    }
</style>

{% endblock %}